### ISSUE TITLE
ipv6支持么 

### ISSUE THREAD

**Issue by duansheli** [iuv/xx#2]
报错
```bash
root@node02:/home/u20# ./xx ip
panic: runtime error: slice bounds out of range [-1:]

goroutine 1 [running]:
github.com/iuv/xx/shell.exe({0x56a62f, 0x4}, {0x56a822, 0x5}, {0x0, 0x0})
        /Users/mac/GolandProjects/xx/shell/ip.go:21 +0x474
github.com/iuv/xx/shell.Ip({0x0, 0x0})
        /Users/mac/GolandProjects/xx/shell/ip.go:14 +0xa5
main.main()
        /Users/mac/GolandProjects/xx/xx.go:27 +0x1b4
root@node02:/home/u20#
```

另外支持 ipv6地址查看么  

下载地址里可以放上加速器的地址 
https://gh.api.99988866.xyz/https://github.com/iuv/xx/blob/master/build/linux/xx

**Comment by iuv** [comment]
ifconfig看一下你本机的网卡是多少，你本机好像不是 en0
```shell
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 38:f9:d3:b0:b1:37
	inet6 fe80::10d9:4931:1d2e:e27b%en0 prefixlen 64 secured scopeid 0x6
	inet 192.168.8.100 netmask 0xffffff00 broadcast 192.168.8.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```

**Comment by duansheli** [comment]
ubuntu v20  ens33

**Comment by iuv** [comment]
获取ipv4修正了一下

ens33是centos类系统默认的网卡

现在兼容了一下，也加了个default模式是输出本地的所有ip

你再试试

ipv6这个暂时不支持了   没有找到好的规则
